import { createGlobalThemeContract } from '@vanilla-extract/css';

export const vars = createGlobalThemeContract(
  {
    color: {
      background: 'color-background',
      brandGlow: 'color-brand-glow',
      error: 'color-error',
      errorContainer: 'color-error-container',
      onBackground: 'color-on-background',
      onError: 'color-on-error',
      onErrorContainer: 'color-on-error-container',
      onPrimary: 'color-on-primary',
      onPrimaryContainer: 'color-on-primary-container',
      onSecondary: 'color-on-secondary',
      onSecondaryContainer: 'color-on-secondary-container',
      onSurface: 'color-on-surface',
      onSurfaceVariant: 'color-on-surface-variant',
      onTertiary: 'color-on-tertiary',
      onTertiaryContainer: 'color-on-tertiary-container',
      onWarning: 'color-on-warning',
      onWarningContainer: 'color-on-warning-container',
      outline: 'color-outline',
      outlineVariant: 'color-outline-variant',
      primary: 'color-primary',
      primaryContainer: 'color-primary-container',
      secondary: 'color-secondary',
      secondaryContainer: 'color-secondary-container',
      surface: 'color-surface',
      surfaceContainer: 'color-surface-container',
      surfaceContainerHigh: 'color-surface-container-high',
      surfaceContainerHighest: 'color-surface-container-highest',
      surfaceContainerLow: 'color-surface-container-low',
      surfaceContainerLowest: 'color-surface-container-lowest',
      surfaceTint: 'color-surface-tint',
      surfaceVariant: 'color-surface-variant',
      tertiary: 'color-tertiary',
      tertiaryContainer: 'color-tertiary-container',
      warning: 'color-warning',
      warningContainer: 'color-warning-container',
    },
    font: {
      display: 'font-display',
      mono: 'font-mono',
      sans: 'font-sans',
    },
  },
  (value) => value || '',
);
