
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async helloWorld(myName: string) : Promise<string> {
    return await TAURI_INVOKE("hello_world", { myName });
},
/**
 * Start the MPV player.
 */
async mpvStart() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the MPV player.
 */
async mpvStop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a media file/URL for playback.
 */
async mpvLoadfile(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_loadfile", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Seek to absolute position in seconds.
 */
async mpvSeek(time: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_seek", { time }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set pause state.
 */
async mpvSetPause(paused: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_set_pause", { paused }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set volume (0-100).
 */
async mpvSetVolume(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_set_volume", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set audio track by ID.
 */
async mpvSetAudioTrack(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_set_audio_track", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set subtitle track by ID.
 */
async mpvSetSubtitleTrack(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_set_subtitle_track", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a property value from MPV.
 */
async mpvGetProperty(name: string) : Promise<Result<PropertyValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_get_property", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current player state.
 */
async mpvGetState() : Promise<Result<PlayerState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mpv_get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if MPV is connected.
 */
async mpvIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("mpv_is_connected");
},
/**
 * Connect to a Jellyfin server.
 */
async jellyfinConnect(credentials: Credentials) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jellyfin_connect", { credentials }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disconnect from Jellyfin server.
 */
async jellyfinDisconnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jellyfin_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get Jellyfin connection state.
 */
async jellyfinGetState() : Promise<ConnectionState> {
    return await TAURI_INVOKE("jellyfin_get_state");
},
/**
 * Check if connected to Jellyfin.
 */
async jellyfinIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("jellyfin_is_connected");
},
/**
 * Get the current session data for saving.
 */
async jellyfinGetSession() : Promise<SavedSession | null> {
    return await TAURI_INVOKE("jellyfin_get_session");
},
/**
 * Restore a session from saved data.
 */
async jellyfinRestoreSession(session: SavedSession) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jellyfin_restore_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear/logout from the current session.
 * 
 * This disconnects from the server and should be paired with
 * clearing the saved session from localStorage on the frontend.
 */
async jellyfinClearSession() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("jellyfin_clear_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current app configuration.
 */
async configGet() : Promise<AppConfig> {
    return await TAURI_INVOKE("config_get");
},
/**
 * Update the app configuration, apply changes live, and persist to disk.
 */
async configSet(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_set", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the default configuration.
 */
async configDefault() : Promise<AppConfig> {
    return await TAURI_INVOKE("config_default");
},
/**
 * Detect MPV path automatically.
 */
async configDetectMpv() : Promise<string | null> {
    return await TAURI_INVOKE("config_detect_mpv");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application configuration.
 */
export type AppConfig = { 
/**
 * Custom MPV executable path (None = auto-detect).
 */
mpvPath?: string | null; 
/**
 * Additional MPV command-line arguments.
 */
mpvArgs?: string[]; 
/**
 * Device name shown in Jellyfin cast menu.
 */
deviceName?: string; 
/**
 * Progress reporting interval in seconds.
 */
progressInterval?: number; 
/**
 * Start minimized to system tray.
 */
startMinimized?: boolean }
/**
 * Connection state exposed to frontend.
 */
export type ConnectionState = { connected: boolean; serverUrl: string | null; serverName: string | null; userName: string | null }
/**
 * Credentials for authentication.
 */
export type Credentials = { serverUrl: string; username: string; password: string }
/**
 * Player state returned to frontend.
 */
export type PlayerState = { connected: boolean; paused: boolean; time_pos: number; duration: number; volume: number }
/**
 * Typed property values from MPV.
 */
export type PropertyValue = boolean | number | string | 
/**
 * Arrays serialized as JSON string for specta compatibility.
 */
string | null
/**
 * Saved session data for persistence.
 */
export type SavedSession = { serverUrl: string; accessToken: string; userId: string; userName: string; serverName: string | null; deviceId: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
