// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Start the MPV player. */
	mpvStart: () => typedError<null, CommandError>(__TAURI_INVOKE("mpv_start")),
	/**  Stop the MPV player. */
	mpvStop: () => typedError<null, CommandError>(__TAURI_INVOKE("mpv_stop")),
	/**  Load a media file/URL for playback. */
	mpvLoadfile: (url: string) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_loadfile", { url })),
	/**  Seek to absolute position in seconds. */
	mpvSeek: (time: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_seek", { time })),
	/**  Set pause state. */
	mpvSetPause: (paused: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_pause", { paused })),
	/**  Set volume (0-100). */
	mpvSetVolume: (volume: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_volume", { volume })),
	/**  Set audio track by ID. */
	mpvSetAudioTrack: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_audio_track", { id })),
	/**  Set subtitle track by ID. */
	mpvSetSubtitleTrack: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_subtitle_track", { id })),
	/**  Get a property value from MPV. */
	mpvGetProperty: (name: string) => typedError<PropertyValue, CommandError>(__TAURI_INVOKE("mpv_get_property", { name })),
	/**  Get current player state. */
	mpvGetState: () => typedError<PlayerState, CommandError>(__TAURI_INVOKE("mpv_get_state")),
	/**  Check if MPV is connected. */
	mpvIsConnected: () => __TAURI_INVOKE<boolean>("mpv_is_connected"),
	/**  Connect to a Jellyfin server. */
	jellyfinConnect: (credentials: Credentials) => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_connect", { credentials })),
	/**  Disconnect from Jellyfin server. */
	jellyfinDisconnect: () => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_disconnect")),
	/**  Get Jellyfin connection state. */
	jellyfinGetState: () => __TAURI_INVOKE<ConnectionState>("jellyfin_get_state"),
	/**  Check if connected to Jellyfin. */
	jellyfinIsConnected: () => __TAURI_INVOKE<boolean>("jellyfin_is_connected"),
	/**  Get the current session data for saving. */
	jellyfinGetSession: () => __TAURI_INVOKE<{
	serverUrl: string,
	accessToken: string,
	userId: string,
	userName: string,
	serverName: string | null,
	deviceId: string | null,
} | null>("jellyfin_get_session"),
	/**  Restore a session from saved data. */
	jellyfinRestoreSession: (session: SavedSession) => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_restore_session", { session })),
	/**
	 *  Clear/logout from the current session.
	 * 
	 *  This disconnects from the server and should be paired with
	 *  clearing the saved session from localStorage on the frontend.
	 */
	jellyfinClearSession: () => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_clear_session")),
	/**  Start a Jellyfin Quick Connect request. */
	jellyfinQuickConnectStart: (serverUrl: string) => typedError<QuickConnectRequest, CommandError>(__TAURI_INVOKE("jellyfin_quick_connect_start", { serverUrl })),
	/**  Check whether a Jellyfin Quick Connect request has been approved. */
	jellyfinQuickConnectCheck: (serverUrl: string, secret: string) => typedError<QuickConnectStatus, CommandError>(__TAURI_INVOKE("jellyfin_quick_connect_check", { serverUrl, secret })),
	/**  Complete Jellyfin Quick Connect authentication. */
	jellyfinQuickConnectAuthenticate: (serverUrl: string, secret: string) => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_quick_connect_authenticate", { serverUrl, secret })),
	/**  Get the current app configuration. */
	configGet: () => __TAURI_INVOKE<AppConfig>("config_get"),
	/**  Update the app configuration, apply changes live, and persist to disk. */
	configSet: (config: AppConfig) => typedError<null, CommandError>(__TAURI_INVOKE("config_set", { config })),
	/**  Get the default configuration. */
	configDefault: () => __TAURI_INVOKE<AppConfig>("config_default"),
	/**  Detect MPV path automatically. */
	configDetectMpv: () => __TAURI_INVOKE<string | null>("config_detect_mpv"),
};

/** Events */
export const events = {
	appNotification: makeEvent<AppNotification>("app-notification"),
};

/* Types */
/**  Application configuration. */
export type AppConfig = {
	/**  Custom MPV executable path (None = auto-detect). */
	mpvPath?: string | null,
	/**  Additional MPV command-line arguments. */
	mpvArgs?: string[],
	/**  Device name shown in Jellyfin cast menu. */
	deviceName?: string,
	/**  Progress reporting interval in seconds. */
	progressInterval?: number,
	/**  Start minimized to system tray. */
	startMinimized?: boolean,
	/**  Enable automatic Intro Skipper plugin skips. */
	introSkipperEnabled?: boolean,
	/**  Keybinding for next episode in MPV. */
	keybindNext?: string,
	/**  Keybinding for previous episode in MPV. */
	keybindPrev?: string,
};

/**  App notification event emitted to frontend. */
export type AppNotification = {
	level: NotificationLevel,
	message: string,
};

/**  Typed command error for better frontend error handling. */
export type CommandError = {
	code: CommandErrorCode,
	message: string,
};

/**  Error codes for frontend to distinguish error types. */
export type CommandErrorCode = 
/**  MPV player is not connected. */
"notConnected" | 
/**  Resource not found (e.g., MPV executable, media file). */
"notFound" | 
/**  Invalid input provided by the caller. */
"invalidInput" | 
/**  Network or connection error. */
"network" | 
/**  Authentication failed. */
"authFailed" | 
/**  Internal error (catch-all). */
"internal";

/**  Connection state exposed to frontend. */
export type ConnectionState = {
	connected: boolean,
	serverUrl: string | null,
	serverName: string | null,
	userName: string | null,
};

/**  Credentials for authentication. */
export type Credentials = {
	serverUrl: string,
	username: string,
	password: string,
};

/**  Notification level for UI display. */
export type NotificationLevel = "error" | "warning" | "info" | "success";

/**  Player state returned to frontend. */
export type PlayerState = {
	connected: boolean,
	paused: boolean,
	time_pos: number | null,
	duration: number | null,
	volume: number | null,
};

/**  Typed property values from MPV. */
export type PropertyValue = boolean | number | null | string | 
/**  Arrays serialized as JSON string for specta compatibility. */
string | "Null";

/**  Quick Connect request created by the server. */
export type QuickConnectRequest = {
	code: string,
	secret: string,
};

/**  Quick Connect request status exposed to the frontend. */
export type QuickConnectStatus = "waiting" | "approved";

/**  Saved session data for persistence. */
export type SavedSession = {
	serverUrl: string,
	accessToken: string,
	userId: string,
	userName: string,
	serverName: string | null,
	deviceId: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

