// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Start the MPV player. */
	mpvStart: () => typedError<null, CommandError>(__TAURI_INVOKE("mpv_start")),
	/**  Stop the MPV player. */
	mpvStop: () => typedError<null, CommandError>(__TAURI_INVOKE("mpv_stop")),
	/**  Load a media file/URL for playback. */
	mpvLoadfile: (url: string) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_loadfile", { url })),
	/**  Seek to absolute position in seconds. */
	mpvSeek: (time: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_seek", { time })),
	/**  Set pause state. */
	mpvSetPause: (paused: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_pause", { paused })),
	/**  Set volume (0-100). */
	mpvSetVolume: (volume: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_volume", { volume })),
	/**  Toggle mute state. */
	mpvToggleMute: () => typedError<null, CommandError>(__TAURI_INVOKE("mpv_toggle_mute")),
	/**  Set audio track by ID. */
	mpvSetAudioTrack: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_audio_track", { id })),
	/**  Set subtitle track by ID, or disable subtitles with a negative ID. */
	mpvSetSubtitleTrack: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("mpv_set_subtitle_track", { id })),
	/**  Get a property value from MPV. */
	mpvGetProperty: (name: string) => typedError<PropertyValue, CommandError>(__TAURI_INVOKE("mpv_get_property", { name })),
	/**  Get current player state. */
	mpvGetState: () => typedError<PlayerState, CommandError>(__TAURI_INVOKE("mpv_get_state")),
	/**  Check if MPV is connected. */
	mpvIsConnected: () => __TAURI_INVOKE<boolean>("mpv_is_connected"),
	/**  Get current user-facing Now Playing state. */
	nowPlayingGetState: () => typedError<NowPlayingState, CommandError>(__TAURI_INVOKE("now_playing_get_state")),
	/**  Load the Library Browser Video Home dashboard data. */
	libraryVideoHome: () => typedError<VideoHome, CommandError>(__TAURI_INVOKE("library_video_home")),
	/**  Load Movies and Shows library shortcuts for Library Browser navigation. */
	libraryVideoShortcuts: () => typedError<VideoLibraryShortcut[], CommandError>(__TAURI_INVOKE("library_video_shortcuts")),
	/**  Load one server-paged Movies or Shows library result page. */
	libraryBrowseVideo: (request: VideoLibraryPageRequest) => typedError<VideoLibraryPage, CommandError>(__TAURI_INVOKE("library_browse_video", { request })),
	/**  Search Movies, Shows, and Episodes with server paging. */
	librarySearchVideo: (request: VideoSearchRequest) => typedError<VideoSearchPage, CommandError>(__TAURI_INVOKE("library_search_video", { request })),
	/**  Load Movie or Episode details for the Library Browser. */
	libraryItemDetail: (itemId: string) => typedError<VideoItemDetail, CommandError>(__TAURI_INVOKE("library_item_detail", { itemId })),
	/**  Load Show details with seasons and the Jellyfin next playable episode. */
	libraryShowDetail: (seriesId: string) => typedError<VideoShowDetail, CommandError>(__TAURI_INVOKE("library_show_detail", { seriesId })),
	/**  Load Episodes for one Show season. */
	librarySeasonEpisodes: (request: VideoSeasonEpisodesRequest) => typedError<VideoSeasonEpisodes, CommandError>(__TAURI_INVOKE("library_season_episodes", { request })),
	/**  Start explicit Library Browser playback through the active Jellyfin session. */
	libraryPlay: (request: VideoLibraryPlayRequest) => typedError<null, CommandError>(__TAURI_INVOKE("library_play", { request })),
	/**  Mutate Jellyfin user data for a Library Browser item. */
	libraryUpdateUserData: (request: VideoUserDataUpdateRequest) => typedError<VideoUserDataUpdate, CommandError>(__TAURI_INVOKE("library_update_user_data", { request })),
	/**  Connect to a Jellyfin server. */
	jellyfinConnect: (credentials: Credentials) => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_connect", { credentials })),
	/**  Disconnect from Jellyfin server. */
	jellyfinDisconnect: () => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_disconnect")),
	/**  Get Jellyfin connection state. */
	jellyfinGetState: () => __TAURI_INVOKE<ConnectionState>("jellyfin_get_state"),
	/**  Check if connected to Jellyfin. */
	jellyfinIsConnected: () => __TAURI_INVOKE<boolean>("jellyfin_is_connected"),
	/**  Get the current session data for saving. */
	jellyfinGetSession: () => __TAURI_INVOKE<{
	provider?: MediaServerProvider,
	serverUrl: string,
	accessToken: string,
	userId: string,
	userName: string,
	serverName: string | null,
	deviceId: string | null,
} | null>("jellyfin_get_session"),
	/**  Restore a session from saved data. */
	jellyfinRestoreSession: (session: SavedSession) => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_restore_session", { session })),
	/**
	 *  Clear/logout from the current session.
	 * 
	 *  This disconnects from the server and should be paired with
	 *  clearing the saved session from localStorage on the frontend.
	 */
	jellyfinClearSession: () => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_clear_session")),
	/**  Play the next episode from the active Jellyfin session. */
	jellyfinPlayNextEpisode: () => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_play_next_episode")),
	/**  Play the previous episode from the active Jellyfin session. */
	jellyfinPlayPreviousEpisode: () => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_play_previous_episode")),
	/**  Start a Jellyfin Quick Connect request. */
	jellyfinQuickConnectStart: (serverUrl: string) => typedError<QuickConnectRequest, CommandError>(__TAURI_INVOKE("jellyfin_quick_connect_start", { serverUrl })),
	/**  Check whether a Jellyfin Quick Connect request has been approved. */
	jellyfinQuickConnectCheck: (serverUrl: string, secret: string) => typedError<QuickConnectStatus, CommandError>(__TAURI_INVOKE("jellyfin_quick_connect_check", { serverUrl, secret })),
	/**  Complete Jellyfin Quick Connect authentication. */
	jellyfinQuickConnectAuthenticate: (serverUrl: string, secret: string) => typedError<null, CommandError>(__TAURI_INVOKE("jellyfin_quick_connect_authenticate", { serverUrl, secret })),
	/**  Connect to the selected media server provider. */
	serverConnect: (credentials: Credentials) => typedError<null, CommandError>(__TAURI_INVOKE("server_connect", { credentials })),
	/**  Disconnect from the active media server provider. */
	serverDisconnect: () => typedError<null, CommandError>(__TAURI_INVOKE("server_disconnect")),
	/**  Get current media server connection state. */
	serverGetState: () => __TAURI_INVOKE<ConnectionState>("server_get_state"),
	/**  Check if a media server provider is connected. */
	serverIsConnected: () => __TAURI_INVOKE<boolean>("server_is_connected"),
	/**  Get the current media server session data for saving. */
	serverGetSession: () => __TAURI_INVOKE<{
	provider?: MediaServerProvider,
	serverUrl: string,
	accessToken: string,
	userId: string,
	userName: string,
	serverName: string | null,
	deviceId: string | null,
} | null>("server_get_session"),
	/**  Restore a media server session from saved data. */
	serverRestoreSession: (session: SavedSession) => typedError<null, CommandError>(__TAURI_INVOKE("server_restore_session", { session })),
	/**  Clear/logout from the current media server session. */
	serverClearSession: () => typedError<null, CommandError>(__TAURI_INVOKE("server_clear_session")),
	/**  Get the current app configuration. */
	configGet: () => __TAURI_INVOKE<AppConfig>("config_get"),
	/**  Update the app configuration, apply changes live, and persist to disk. */
	configSet: (config: AppConfig) => typedError<null, CommandError>(__TAURI_INVOKE("config_set", { config })),
	/**  Get the default configuration. */
	configDefault: () => __TAURI_INVOKE<AppConfig>("config_default"),
	/**  Detect MPV path automatically. */
	configDetectMpv: () => __TAURI_INVOKE<string | null>("config_detect_mpv"),
};

/** Events */
export const events = {
	appNotification: makeEvent<AppNotification>("app-notification"),
	nowPlayingChanged: makeEvent<NowPlayingChanged>("now-playing-changed"),
};

/* Types */
/**  Reason an adjacent episode control is unavailable. */
export type AdjacentEpisodeUnavailableReason = "noSession" | "noCurrentItem" | "notEpisode" | "unknown";

/**  Application configuration. */
export type AppConfig = {
	/**  Custom MPV executable path (None = auto-detect). */
	mpvPath?: string | null,
	/**  Additional MPV command-line arguments. */
	mpvArgs?: string[],
	/**  Device name shown in Jellyfin cast menu. */
	deviceName?: string,
	/**  Progress reporting interval in seconds. */
	progressInterval?: number,
	/**  Start minimized to system tray. */
	startMinimized?: boolean,
	/**  Intro Skipper plugin behavior mode. */
	introSkipperMode?: IntroSkipperMode,
	/**  Ordered subtitle language codes to prefer when Jellyfin does not request a track. */
	preferredSubtitleLanguages?: string[],
	/**  Keybinding for next episode in MPV. */
	keybindNext?: string,
	/**  Keybinding for previous episode in MPV. */
	keybindPrev?: string,
	/**  Keybinding for manual Intro Skipper seek in MPV. */
	keybindIntroSkip?: string,
};

/**  App notification event emitted to frontend. */
export type AppNotification = {
	level: NotificationLevel,
	message: string,
};

/**  Typed command error for better frontend error handling. */
export type CommandError = {
	code: CommandErrorCode,
	message: string,
};

/**  Error codes for frontend to distinguish error types. */
export type CommandErrorCode = 
/**  MPV player is not connected. */
"notConnected" | 
/**  Resource not found (e.g., MPV executable, media file). */
"notFound" | 
/**  Invalid input provided by the caller. */
"invalidInput" | 
/**  Network or connection error. */
"network" | 
/**  Authentication failed. */
"authFailed" | 
/**  Internal error (catch-all). */
"internal";

/**  Connection state exposed to frontend. */
export type ConnectionState = {
	provider: MediaServerProvider,
	capabilities: ProviderCapabilities,
	connected: boolean,
	serverUrl: string | null,
	serverName: string | null,
	userName: string | null,
};

/**  Credentials for authentication. */
export type Credentials = {
	provider?: MediaServerProvider,
	serverUrl: string,
	username: string,
	password: string,
};

/**  Intro Skipper behavior mode. */
export type IntroSkipperMode = "automatic" | "manual" | "off";

/**  Media server provider selected for a connection or saved session. */
export type MediaServerProvider = "jellyfin" | "emby";

/**  Notification level for UI display. */
export type NotificationLevel = "error" | "warning" | "info" | "success";

/**  Now Playing state event emitted to frontend. */
export type NowPlayingChanged = {
	state: NowPlayingState,
};

/**  Minimal current media metadata safe for UI display. */
export type NowPlayingMedia = {
	itemId: string,
	name: string,
	itemType: string,
	seriesName: string | null,
	seasonNumber: number | null,
	episodeNumber: number | null,
};

/**  User-facing playback state for the Operations Console. */
export type NowPlayingState = {
	status: NowPlayingStatus,
	player: PlayerState,
	media: NowPlayingMedia | null,
	canPlayNext: boolean,
	canPlayPrevious: boolean,
	nextUnavailableReason: AdjacentEpisodeUnavailableReason | null,
	previousUnavailableReason: AdjacentEpisodeUnavailableReason | null,
};

/**  User-facing Now Playing status. */
export type NowPlayingStatus = "offline" | "idle" | "playing" | "paused" | "unknown";

/**  Player transport state returned to frontend. */
export type PlayerState = {
	connected: boolean,
	paused: boolean,
	muted: boolean,
	timePos: number | null,
	duration: number | null,
	volume: number | null,
};

/**  Typed property values from MPV. */
export type PropertyValue = boolean | number | null | string | 
/**  Arrays serialized as JSON string for specta compatibility. */
string | "Null";

/**  Feature capabilities exposed by the active or selected media server provider. */
export type ProviderCapabilities = {
	quickConnect: boolean,
	introSkipper: boolean,
	remoteControl: boolean,
	remoteControlAvailable: boolean,
	remoteControlWarning: string | null,
};

/**  Quick Connect request created by the server. */
export type QuickConnectRequest = {
	code: string,
	secret: string,
};

/**  Quick Connect request status exposed to the frontend. */
export type QuickConnectStatus = "waiting" | "approved";

/**  Saved session data for persistence. */
export type SavedSession = {
	provider?: MediaServerProvider,
	serverUrl: string,
	accessToken: string,
	userId: string,
	userName: string,
	serverName: string | null,
	deviceId: string | null,
};

/**  Library Browser landing data exposed to the frontend. */
export type VideoHome = {
	continueWatching: VideoHomeItem[],
	nextUp: VideoHomeItem[],
	latestMovies: VideoHomeItem[],
	latestEpisodes: VideoHomeItem[],
};

/**  Video item summary for Video Home rows. */
export type VideoHomeItem = {
	id: string,
	name: string,
	itemType: string,
	seriesId: string | null,
	seriesName: string | null,
	seasonNumber: number | null,
	episodeNumber: number | null,
	productionYear: number | null,
	runtimeSeconds: number | null,
	resumePositionSeconds: number | null,
	playedPercentage: number | null,
	played: boolean,
	favorite: boolean,
	artworkUrl: string | null,
};

/**  Playable Movie or Episode detail data exposed to the frontend. */
export type VideoItemDetail = {
	id: string,
	name: string,
	itemType: string,
	overview: string | null,
	productionYear: number | null,
	runtimeSeconds: number | null,
	seriesId: string | null,
	seriesName: string | null,
	seasonNumber: number | null,
	episodeNumber: number | null,
	genres: string[],
	played: boolean,
	favorite: boolean,
	playedPercentage: number | null,
	resumePositionSeconds: number | null,
	canResume: boolean,
	canPlay: boolean,
	artworkUrl: string | null,
	audioStreams: VideoPlaybackStreamOption[],
	subtitleStreams: VideoPlaybackStreamOption[],
};

/**  Media card summary for Movies and Shows browse results, and episode rows. */
export type VideoLibraryItem = {
	id: string,
	name: string,
	itemType: string,
	productionYear: number | null,
	runtimeSeconds: number | null,
	played: boolean,
	favorite: boolean,
	artworkUrl: string | null,
	/**  Episode metadata: season number (1-based), available for Episode items. */
	seasonNumber: number | null,
	/**  Episode metadata: episode number within season (1-based), available for Episode items. */
	episodeNumber: number | null,
	/**  Episode metadata: parent series id, available for Episode items. */
	seriesId: string | null,
	/**  Episode metadata: parent series name, available for Episode items. */
	seriesName: string | null,
	/**  Resume position in seconds, populated for episode rows. */
	resumePositionSeconds: number | null,
	/**  Percentage watched (0–100), populated for episode rows. */
	playedPercentage: number | null,
};

/**  Supported video library browse families. */
export type VideoLibraryKind = "movies" | "tvshows";

/**  Paged Library Browser listing result. */
export type VideoLibraryPage = {
	libraryId: string,
	collectionType: VideoLibraryKind,
	startIndex: number,
	limit: number,
	totalRecordCount: number,
	hasMore: boolean,
	items: VideoLibraryItem[],
};

/**  Paged Library Browser listing request. */
export type VideoLibraryPageRequest = {
	libraryId: string,
	collectionType: VideoLibraryKind,
	startIndex: number,
	limit: number,
	sort: VideoLibrarySort,
	playedFilter: VideoLibraryPlayedFilter,
	favoritesOnly: boolean,
};

/**  Library Browser playback mode selected by the user. */
export type VideoLibraryPlayMode = "resume" | "start" | "show";

/**  Explicit Library Browser playback launch request. */
export type VideoLibraryPlayRequest = {
	itemId: string,
	mode: VideoLibraryPlayMode,
	startPositionSeconds: number | null,
	audioStreamIndex: number | null,
	subtitleStreamIndex: number | null,
};

/**  Supported played-state filters for Library Browser results. */
export type VideoLibraryPlayedFilter = "all" | "played" | "unplayed";

/**  Video library shortcut for drilling into Movies or Shows libraries. */
export type VideoLibraryShortcut = {
	id: string,
	name: string,
	collectionType: string,
	itemCount: number | null,
	artworkUrl: string | null,
};

/**  Supported Library Browser sort options. */
export type VideoLibrarySort = "title" | "recentlyAdded" | "releaseDate";

/**  Selectable audio or subtitle stream exposed before Library playback starts. */
export type VideoPlaybackStreamOption = {
	index: number,
	label: string,
	language: string | null,
	codec: string | null,
	isDefault: boolean,
	isExternal: boolean,
};

/**  Paged video-only Library search result. */
export type VideoSearchPage = {
	query: string,
	startIndex: number,
	limit: number,
	totalRecordCount: number,
	hasMore: boolean,
	items: VideoLibraryItem[],
};

/**  Paged video-only Library search request. */
export type VideoSearchRequest = {
	query: string,
	startIndex: number,
	limit: number,
};

/**  Season summary for a Show detail page. */
export type VideoSeason = {
	id: string,
	name: string,
	seasonNumber: number | null,
	played: boolean,
	favorite: boolean,
	artworkUrl: string | null,
};

/**  Episode list for a selected season. */
export type VideoSeasonEpisodes = {
	seriesId: string,
	seasonId: string | null,
	seasonNumber: number | null,
	episodes: VideoLibraryItem[],
};

/**  Request for episodes inside a show season. */
export type VideoSeasonEpisodesRequest = {
	seriesId: string,
	seasonId: string | null,
	seasonNumber: number | null,
};

/**  Show detail data with seasons and Jellyfin next playable episode. */
export type VideoShowDetail = {
	id: string,
	name: string,
	overview: string | null,
	productionYear: number | null,
	genres: string[],
	played: boolean,
	favorite: boolean,
	canPlay: boolean,
	artworkUrl: string | null,
	nextEpisode: VideoLibraryItem | null,
	seasons: VideoSeason[],
};

/**  User data action supported by Library Browser detail views. */
export type VideoUserDataAction = "favorite" | "unfavorite" | "markPlayed" | "markUnplayed";

/**  Updated user data returned by Jellyfin after a mutation succeeds. */
export type VideoUserDataUpdate = {
	itemId: string,
	played: boolean,
	favorite: boolean,
};

/**  User-scoped Jellyfin user data mutation request. */
export type VideoUserDataUpdateRequest = {
	itemId: string,
	action: VideoUserDataAction,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

